language: node_js
node_js:
  - "12"
# whitelist
branches:
  only:
    - master
install:
  - npm install
stages:
  - test
  - build
jobs:
  include:
    - stage: test
      script: 
        - npm run test
    - stage: build
      script: 
        - npm run build
after_script:
  - npm run coverage
